---
- hosts: nginx2
  become: yes
  become_user: root
  tasks:
  - name: Install Epel-Release
    yum: name=epel-release state=latest
  - name: Install nginx
    yum: name=nginx state=latest
  - name: Configure Nginx
    template: src=nginx2.conf.j2 dest=/etc/nginx/conf.d/default.conf
  - name: Make sure Nginx is started
    service: name=nginx state=started enabled=yes
  - name: Install redis
    yum: name=redis state=latest
  - name: Configure Redis
    template: src=redis.conf.j2 dest=/etc/redis.conf
  - name: Make sure Redis is started
    service: name=redis state=started enabled=yes
