---
- hosts: nginx1
  become: yes
  become_user: root
  tasks:
  - name: Install Epel-Release
    yum: name=epel-release state=latest
  - name: Install nginx
    yum: name=nginx state=latest
  - name: Configure Nginx
    template: src=nginx1.conf.j2 dest=/etc/nginx/conf.d/default.conf
  - name: Make sure Nginx is started
    service: name=nginx state=started enabled=yes
