---
- hosts: redis
  become: yes
  become_user: root
  tasks:
  - name: Install Epel-Release
    yum: name=epel-release state=latest
  - name: Install redis
    yum: name=redis state=latest
  - name: Configure Redis
    template: src=redis.conf.j2 dest=/etc/redis.conf
  - name: Make sure Nginx is started
    service: name=redis state=started enabled=yes

